### ISSUE TITLE
Still doesn't pass WCAG 2.1

### ISSUE THREAD

**Issue by huangqun** [nmackey/accessible-nprogress#10]
I'm getting the following error when running accessibility testing, can this be addressed?

![AXE_Accessibility_Results_2021-01-30_13-03-47](https://user-images.githubusercontent.com/6045894/106396103-c7145f00-63ba-11eb-9f98-288839c5cbfe.png)

**Comment by nmackey** [comment]
I just released a fix for this as version 2.1.0 - https://www.npmjs.com/package/accessible-nprogress

Let me know if this fixes your issue.

**Comment by nmackey** [comment]
It now has a default aria-label for both the bar & spinner as 'processing request'
This can be customized with the new `barLabel` & `spinnerLabel` config options.
https://github.com/nmackey/accessible-nprogress#barlabel-and-spinnerlabel

**Comment by huangqun** [comment]
Thanks @nmackey, that fixed the issue I posted but after upgrading to v2.1.0 a new one came up which still seemed to require some changes to the lib itself:

<img width="1220" alt="axe" src="https://user-images.githubusercontent.com/6045894/106415031-f222a100-6402-11eb-8b19-ebac24109361.png">

**Comment by nmackey** [comment]
That can be fixed on your side, by default the progress bar is attached to the body (since the library doesn't know your DOM structure), but you can attach it wherever you want using the 'parent' config option.  That error is asking for you to put it in a landmark element... such as header, main, footer, or nav element.
https://dequeuniversity.com/rules/axe/3.5/region?application=AxeChrome

You can look at my setup of my acceptance test, which uses axe.
https://github.com/nmackey/accessible-nprogress/blob/master/test-acceptance/index.html

**Comment by huangqun** [comment]
That makes good sense, thanks a lot!
